'use strict';var kn=function(){if(!Zb)return!1;try{return new ActiveXObject("MSXML2.DOMDocument"),!0}catch(a){return!1}};Zb&&kn();var ln=function(a,b){Qc.call(this);this.RS=a||0;this.Ql=b||10;if(this.RS>this.Ql)throw Error("[goog.structs.Pool] Min can not be greater than max");this.ad=new El;this.Hj=new Ee;this.NB=0;this.IE=null;this.wu()};v(ln,Qc);d=ln.prototype;d.getObject=function(){var a=u();if(!(null!=this.IE&&a-this.IE<this.NB)){var b=this.Ofa();b&&(this.IE=a,this.Hj.add(b));return b}};d.tm=function(a){return this.Hj.remove(a)?(this.BA(a),!0):!1};
d.Ofa=function(){for(var a;0<this.lO()&&(a=this.ad.Wk(),!this.zF(a));)this.wu();!a&&this.ma()<this.Ql&&(a=this.Ph());return a};d.BA=function(a){this.Hj.remove(a);this.zF(a)&&this.ma()<this.Ql?this.ad.enqueue(a):this.Xk(a)};d.wu=function(){for(var a=this.ad;this.ma()<this.RS;)a.enqueue(this.Ph());for(;this.ma()>this.Ql&&0<this.lO();)this.Xk(a.Wk())};d.Ph=function(){return{}};d.Xk=function(a){if("function"==typeof a.fb)a.fb();else for(var b in a)a[b]=null};
d.zF=function(a){return"function"==typeof a.N1?a.N1():!0};d.contains=function(a){return this.ad.contains(a)||this.Hj.contains(a)};d.ma=function(){return this.ad.ma()+this.Hj.ma()};d.z6=function(){return this.Hj.ma()};d.lO=function(){return this.ad.ma()};d.Ec=function(){return this.ad.Ec()&&this.Hj.Ec()};d.aa=function(){ln.W.aa.call(this);if(0<this.z6())throw Error("[goog.structs.Pool] Objects not released");delete this.Hj;for(var a=this.ad;!a.Ec();)this.Xk(a.Wk());delete this.ad};var mn=function(a,b){this.eh=a;this.Qe=b};mn.prototype.getKey=function(){return this.eh};mn.prototype.bc=function(){return this.Qe};mn.prototype.clone=function(){return new mn(this.eh,this.Qe)};var nn=function(a){this.rf=[];a&&this.e$(a)};d=nn.prototype;d.insert=function(a,b){var c=this.rf;c.push(new mn(a,b));this.fba(c.length-1)};d.e$=function(a){var b;if(a instanceof nn){if(b=a.xb(),a=a.T(),0>=this.ma()){for(var c=this.rf,e=0;e<b.length;e++)c.push(new mn(b[e],a[e]));return}}else b=Eb(a),a=Db(a);for(e=0;e<b.length;e++)this.insert(b[e],a[e])};d.remove=function(){var a=this.rf,b=a.length,c=a[0];if(!(0>=b))return 1==b?ib(a):(a[0]=a.pop(),this.eba(0)),c.bc()};
d.eba=function(a){for(var b=this.rf,c=b.length,e=b[a];a<c>>1;){var f=this.G6(a),h=this.L7(a),f=h<c&&b[h].getKey()<b[f].getKey()?h:f;if(b[f].getKey()>e.getKey())break;b[a]=b[f];a=f}b[a]=e};d.fba=function(a){for(var b=this.rf,c=b[a];0<a;){var e=this.f7(a);if(b[e].getKey()>c.getKey())b[a]=b[e],a=e;else break}b[a]=c};d.G6=function(a){return 2*a+1};d.L7=function(a){return 2*a+2};d.f7=function(a){return a-1>>1};d.T=function(){for(var a=this.rf,b=[],c=a.length,e=0;e<c;e++)b.push(a[e].bc());return b};
d.xb=function(){for(var a=this.rf,b=[],c=a.length,e=0;e<c;e++)b.push(a[e].getKey());return b};d.Kn=function(a){return bb(this.rf,function(b){return b.bc()==a})};d.Wa=function(a){return bb(this.rf,function(b){return b.getKey()==a})};d.clone=function(){return new nn(this)};d.ma=function(){return this.rf.length};d.Ec=function(){return hb(this.rf)};d.clear=function(){ib(this.rf)};var on=function(){nn.call(this)};v(on,nn);on.prototype.enqueue=function(a,b){this.insert(a,b)};on.prototype.Wk=function(){return this.remove()};var pn=function(a,b){this.YL=void 0;this.hy=new on;ln.call(this,a,b)};v(pn,ln);d=pn.prototype;d.getObject=function(a,b){if(!a)return(a=pn.W.getObject.call(this))&&this.NB&&(this.YL=g.setTimeout(t(this.xw,this),this.NB)),a;this.hy.enqueue(l(b)?b:100,a);this.xw()};d.xw=function(){for(var a=this.hy;0<a.ma();){var b=this.getObject();if(b)a.Wk().apply(this,[b]);else break}};d.BA=function(a){pn.W.BA.call(this,a);this.xw()};d.wu=function(){pn.W.wu.call(this);this.xw()};
d.aa=function(){pn.W.aa.call(this);g.clearTimeout(this.YL);this.hy.clear();this.hy=null};var qn=function(a,b,c,e){this.cc=a;this.Xi=!!e;pn.call(this,b,c)};v(qn,pn);qn.prototype.Ph=function(){var a=new Kf,b=this.cc;b&&b.forEach(function(b,e){a.headers.set(e,b)});this.Xi&&a.fz(!0);return a};qn.prototype.zF=function(a){return!a.isDisposed()&&!a.Zf()};var rn=function(a,b,c,e,f,h){F.call(this);this.vd=l(a)?a:1;this.Ti=l(f)?Math.max(0,f):0;this.Xi=!!h;this.iq=new qn(b,c,e,h);this.Ic=new H;this.Pa=new Cl(this)};v(rn,F);var sn="ready complete success error abort timeout".split(" ");d=rn.prototype;d.At=function(a){this.Ti=Math.max(0,a)};
d.send=function(a,b,c,e,f,h,k,n,q,z){if(this.Ic.get(a))throw Error("[goog.net.XhrManager] ID in use");b=new tn(b,t(this.M8,this,a),c,e,f,k,l(n)?n:this.vd,q,l(z)?z:this.Xi);this.Ic.set(a,b);a=t(this.B8,this,a);this.iq.getObject(a,h);return b};d.abort=function(a,b){var c=this.Ic.get(a);if(c){var e=c.hA;c.Fha(!0);b&&(e&&(this.OU(e,c.pJ),rd(e,"ready",function(){this.iq.tm(e)},!1,this)),this.Ic.remove(a));e&&e.abort()}};
d.B8=function(a,b){var c=this.Ic.get(a);c&&!c.hA?(this.z0(b,c.pJ),b.At(this.Ti),b.XH(c.jk),b.fz(c.Xi),c.hA=b,this.dispatchEvent(new un("ready",this,a,b)),this.bV(a,b),c.RJ&&b.abort()):this.iq.tm(b)};d.M8=function(a,b){var c=b.target;switch(b.type){case "ready":this.bV(a,c);break;case "complete":return this.H8(a,c,b);case "success":this.A9(a,c);break;case "timeout":case "error":this.ah(a,c);break;case "abort":this.z8(a,c)}return null};
d.bV=function(a,b){var c=this.Ic.get(a);!c||c.uL||c.qE()?(c&&(this.OU(b,c.pJ),this.Ic.remove(a)),this.iq.tm(b)):(c.U9(),b.send(c.getUrl(),c.Yaa,c.lc,c.jl()))};d.H8=function(a,b,c){var e=this.Ic.get(a);if(7==b.Kj||b.Od()||e.qE())if(this.dispatchEvent(new un("complete",this,a,b)),e&&(e.kia(!0),e.tL))return e.tL.call(b,c);return null};d.z8=function(a,b){this.dispatchEvent(new un("abort",this,a,b))};d.A9=function(a,b){this.dispatchEvent(new un("success",this,a,b))};
d.ah=function(a,b){this.Ic.get(a).qE()&&this.dispatchEvent(new un("error",this,a,b))};d.OU=function(a,b,c){this.Pa.Hd(a,c||sn,b)};d.z0=function(a,b,c){this.Pa.listen(a,c||sn,b)};d.aa=function(){rn.W.aa.call(this);this.iq.fb();this.iq=null;this.Pa.fb();this.Pa=null;this.Ic.clear();this.Ic=null};var un=function(a,b,c,e){E.call(this,a,b);this.id=c;this.hA=e};v(un,E);
var tn=function(a,b,c,e,f,h,k,n,q){this.eu=a;this.Yaa=c||"GET";this.lc=e;this.cc=f||null;this.vd=l(k)?k:1;this.yK=0;this.RJ=this.uL=!1;this.pJ=b;this.tL=h;this.jk=n||"";this.Xi=!!q;this.hA=null};d=tn.prototype;d.getUrl=function(){return this.eu};d.jl=function(){return this.cc};d.Ug=function(){return this.vd};d.U9=function(){this.yK++};d.qE=function(){return this.yK>this.vd};d.kia=function(a){this.uL=a};d.Fha=function(a){this.RJ=a};var vn=function(){this.name="unknown";this.state="error";this.i$=null;this.allowStop=!0;this.nh=null;this.extraData={}},wn=function(a,b){this.jZ=a;this.Eh=b;this.Qga=!!b&&"running"==b.state},zn=function(a,b,c){void 0===b&&(xn||(xn=new rn(3,null,1,10,2E3)),b=xn);void 0===c&&(yn||(yn=new rn(0,null,1,10,15E3)),c=yn);this.sg=a;this.hq=b;this.jq=[];this.kZ=c;this.a=D("mr.dial.Client")};d=zn.prototype;d.abort=function(){var a=this;this.jq.forEach(function(b){a.hq.abort(b,!0);a.kZ.abort(b,!0)})};
d.launchApp=function(a,b){var c=new Ec,e=(++An).toString();this.jq.push(e);this.kZ.send(e,this.rC(a),"POST",b,null,0,this.KM("launchApp","POST",e,c));return c.promise};d.BX=function(a){var b=new Ec,c=(++An).toString();this.jq.push(c);this.hq.send(c,this.rC(a),"DELETE",null,null,0,this.KM("stopApp","DELETE",c,b),0);return b.promise};d.pC=function(a){var b=this;return new Promise(function(c){var e=(++An).toString();b.jq.push(e);b.hq.send(e,b.rC(a),"GET",null,null,0,t(b.Xba,b,e,c))})};
d.Xba=function(a,b,c){nb(this.jq,a);a=c.target;He(this.a,"GetAppInfo","GET",a,!0);if(a.Od())if(c=(c=a.ff())?Ie(c):null){var e=c.getElementsByTagName("service");if(e&&1==e.length){c=new vn;for(var f=0,h=e[0].childNodes.length;f<h;f++){var k=e[0].childNodes[f];if("state"==k.nodeName){a:switch(k.textContent){case "running":k="running";break a;case "stopped":k="stopped";break a;default:k="error"}c.state=k}else"name"==k.nodeName?c.name=k.textContent:"link"==k.nodeName?c.nh=k.getAttribute("href"):"options"==
k.nodeName?c.allowStop="false"!=k.getAttribute("allowStop"):c.extraData[k.nodeName]=k.innerHTML}if("unknown"==c.name)this.a.info("GET response missing name value"),b(new wn(a,null));else if("error"==c.state)this.a.info("GET response missing state value"),b(new wn(a,null));else{if((e=/installable=(.+)/.exec(c.state))&&e[1])c.state="installable",c.i$=e[1];else if("running"!=c.state&&"stopped"!=c.state){this.a.info("GET response has invalid state value");b(new wn(a,null));return}b(new wn(a,c))}}else this.a.info("Invalid GET response (invalid service)"),
b(new wn(a,null))}else this.a.info("Invalid or empty response"),b(new wn(a,null));else this.a.info("Request to "+a.iw()+" failed"),b(new wn(a,null))};d.rC=function(a){var b=this.sg.qj;"/"!=b.charAt(b.length-1)&&(b+="/");return b+a};d.KM=function(a,b,c,e){var f=this;return function(h){nb(f.jq,c);h=h.target;He(f.a,a,b,h,!0);h.Od()?e.resolve(void 0):e.reject(Error(hf(h.Kj)))}};var xn=null,yn=null,An=999;var Bn=function(a,b,c){this.appName=b;this.launchParameter=void 0===c?"":c},Dn=function(a){if(a.startsWith("urn:dial-multiscreen-org:dial:application:")){var b=a.indexOf("?"),c=a.substring(42,0<b?b:void 0);a=c&&0<c.length?new Bn(a,c,0<b?a.substring(b+1):void 0):null}else a=Cn(a);return a},Cn=function(a){var b=(new Vj(a)).fl;if(!b)return null;var c=En.exec(b),c=c?c[1]:null;if(!c)return null;c=decodeURIComponent(c);if(b=(b=Fn.exec(b))?b[1]:void 0)try{b=Ki(b)}catch(e){return Gn.u("Invalid base64 encoded postData:"+
b),null}return new Bn(a,c,b)},Gn=D("mr.dial.MediaSource"),En=/__dialAppName__=([A-Za-z0-9-._~!$&'()*+,;=%]+)/,Fn=/__dialPostData__=([A-Za-z0-9]+={0,2})/;var Hn=function(a,b){this.Gb=a;this.appName=b};var In=function(a){this.He=new Map;this.yA=a};d=In.prototype;d.init=function(){Wh(this)};d.clear=function(){this.He.clear()};d.add=function(a){this.sN(a.Gb.id)||(this.He.set(a.Gb.id,a),this.yA.nba(a))};d.sN=function(a){return this.He.get(a)||null};d.tN=function(a){for(var b=ia(this.He),c=b.next();!c.done;c=b.next())if(c=ia(c.value),c.next(),c=c.next().value,c.Gb.sinkId==a)return c;return null};d.Lfa=function(a){if(a=this.tN(a))this.He.delete(a.Gb.id),this.yA.iT(a)};
d.KU=function(a){var b=this.He.get(a);b&&(this.He.delete(a),this.yA.iT(b))};d.li=function(){return Array.from(this.He.values(),function(a){return a.Gb})};d.Z4=function(){return Array.from(this.He.values())};d.Ca=function(){return"dial.ActivityRecords"};d.getData=function(){return[Array.from(this.He)]};d.tb=function(){var a=Th(this);a&&(this.He=new Map(a))};var Jn={Gpa:0,ssa:1,qra:2,Fpa:3},Kn={ERROR:0,Jra:1,EMPTY:2},Ln=function(a){gh("MediaRouter.Dial.Create.Route",a,Jn)},Mn=function(a){gh("MediaRouter.Dial.Device.Description.Failure",a,Kn)};var Nn=/^([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$/,On=[4278190080,4293918720,4294901760],Pn=[167772160,2886729728,3232235520],Qn=function(a){var b=document.createElement("a");b.href=a;return b};var Rn=function(){this.configId=this.modelName=this.deviceType=this.expireTimeMillis=this.fetchTimeMillis=this.appUrl=this.ipAddress=this.friendlyName=this.deviceLabel=this.uniqueId=null};
Rn.prototype.Sz=function(){var a;if(this.deviceLabel)if(this.uniqueId)if(this.friendlyName)if(this.ipAddress)if(this.appUrl)if(this.fetchTimeMillis)if(this.expireTimeMillis){a=this.ipAddress;var b=Qn(this.appUrl);a="http:"==b.protocol&&b.hostname==a?null:"Invalid appUrl"}else a="Missing expireTimeMillis";else a="Missing fetchTimeMillis";else a="Missing appUrl";else a="Missing ipAddress";else a="Missing friendlyName";else a="Missing uniqueId";else a="Missing deviceLabel";return a};
Rn.prototype.toString=function(){return JSON.stringify(this,function(a,b){return p(b)&&0==b.indexOf("uuid:")?"***":b})};
var Sn=function(a){var b=new Rn;b.uniqueId=a.uniqueId;b.deviceLabel=a.deviceLabel;b.friendlyName=a.friendlyName;b.ipAddress=a.ipAddress;b.appUrl=a.appUrl;b.fetchTimeMillis=a.fetchTimeMillis;b.expireTimeMillis=a.expireTimeMillis;b.deviceType=a.deviceType;b.modelName=a.modelName;b.configId=a.configId;return b},Vn=function(a){this.zq=new Map;this.uc=new Map;this.jG=new Map;var b;(b=a)||(Tn||(Tn=new rn(3,null,1,10,2E3)),b=Tn);this.hq=b;a||(Un||(Un=new rn(2,null,1,10,3E3)),a=Un);this.T_=a;this.a=D("mr.dial.DeviceDescriptionService");
Wh(this)};d=Vn.prototype;d.Ca=function(){return"mr.dial.DeviceDescriptionService"};d.getData=function(){return[Array.from(this.zq)]};d.tb=function(){var a=Th(this);if(a)for(var a=ia(a),b=a.next();!b.done;b=a.next()){var c=ia(b.value),b=c.next().value,c=c.next().value;null!=Sn(c).Sz()?this.a.error("Dropping invalid description "+b+" loaded from storage."):this.zq.set(b,Sn(c))}};d.c6=function(a){var b=this.a2(a);return b?(fh("MediaRouter.Dial.Device.Description.Cached"),Promise.resolve(b)):this.x4(a)};
d.S_=function(a){var b=this.uc.get(a);b&&(this.hq.abort(a,!0),b.Pb.reject(Error("Aborted")))};d.a2=function(a){var b=this.zq.get(a.deviceLabel);return b?b.configId!=a.configId||Date.now()>=b.expireTimeMillis?(this.a.C("Removing invalid entry "+b.toString()),this.zq.delete(a.deviceLabel),null):b:null};
d.x4=function(a){var b=this;if(!Wn(a.deviceDescriptionUrl))return Promise.reject(Error("Invalid device description URL: "+a.deviceDescriptionUrl));var c=this.uc.get(a.deviceLabel);if(c){if(c.deviceDescriptionUrl==a.deviceDescriptionUrl)return c.Pb.promise;this.S_(a.deviceLabel)}var e=new Ec,c={deviceDescriptionUrl:a.deviceDescriptionUrl,Pb:e};this.uc.set(a.deviceLabel,c);chrome.dial.fetchDeviceDescription?chrome.dial.fetchDeviceDescription(a.deviceLabel,function(c){b.uc.delete(a.deviceLabel);c?(c=
b.nU(a,c.deviceDescription,c.appUrl))?e.resolve(c):e.reject(Error("Failed to process fetch result")):e.reject(chrome.runtime.lastError&&chrome.runtime.lastError.message?Error("chrome.dial.fetchDeviceDescription failed, chrome.runtime.lastError: "+chrome.runtime.lastError.message):Error("chrome.dial.fetchDeviceDescription failed, chrome.runtime.lastError: Unknown error"))}):this.hq.send(a.deviceLabel,a.deviceDescriptionUrl,"GET",null,null,0,function(c){b.uc.delete(a.deviceLabel);(c=b.F9(a,c))?e.resolve(c):
e.reject(Error("Failed to get device description"))});return e.promise};d.F9=function(a,b){var c=b.target;He(this.a,"fetchDeviceDescription","GET",c);if(!c.Od())return this.a.info("Request to "+c.iw()+" failed"),Mn(0),null;b=c.ff();if(!b)return this.a.info("Invalid or empty response"),Mn(2),null;c=c.getResponseHeader("Application-URL");return c?this.nU(a,b,c):(this.a.info("Invalid or empty AppURL"),Mn(2),null)};
d.nU=function(a,b,c){b=this.vda(a,b,c);if(!b)return Mn(1),this.a.info("Invalid device description"),null;this.a.info("Got device description for "+b.deviceLabel);this.a.C("... device description was: "+b.toString());null!=b.configId&&(this.a.C("Caching device description for "+b.deviceLabel),this.zq.set(a.deviceLabel,b));return b};
d.vda=function(a,b,c){var e=Ie(b);if(!e)return null;var f=new Rn;f.fetchTimeMillis=Date.now();f.expireTimeMillis=f.fetchTimeMillis+18E5;f.deviceLabel=a.deviceLabel;f.configId=a.configId;a=Qn(a.deviceDescriptionUrl);f.ipAddress=a.hostname;f.deviceType=Xn(e,"deviceType");f.modelName=Xn(e,"modelName");f.friendlyName=Xn(e,"friendlyName");f.uniqueId=Xn(e,"UDN");!f.friendlyName&&f.modelName&&(f.friendlyName=f.modelName,f.uniqueId&&(f.friendlyName+="["+f.uniqueId.slice(-4)+"]"),this.a.u("Fixed device description: created friendlyName from modelName."));
f.appUrl=c;c=f.Sz();this.a.C(function(){return"Device description: "+Yn(e)});return c?(this.a.u(function(){return"Device description failed to validate: "+f},c),null):f};var Xn=function(a,b){return(a=a.getElementsByTagName(b))&&0!=a.length?a[0].textContent:null},Yn=function(a){var b=function(a){for(var b=0,c=a.length;b<c;b++)a[b].textContent="***"};b(a.getElementsByTagName("UDN"));b(a.getElementsByTagName("serialNumber"));return(new XMLSerializer).serializeToString(a)};
Vn.prototype.Cq=function(a){var b=this,c=this.jG.get(a);if(c)return c.promise;c=new Ec;this.jG.set(a,c);this.T_.send(a,a,"GET",null,null,0,function(e){b.jG.delete(a);e=e.target;He(b.a,"checkAccess","GET",e,!1);c.resolve(e.Od())});return c.promise};
var Wn=function(a){a=Qn(a);var b;if(b="http:"==a.protocol)a:{b:if((a=a.hostname.match(Nn))&&5==a.length){b=[];for(var c=0;4>c;c++)if(b[c]=Number.parseInt(a[c+1],10),0>b[c]||255<b[c]){a=null;break b}a=b}else a=null;if(a)for(a=(a[0]<<24|a[1]<<16|a[2]<<8|a[0])>>>0,b=0;3>b;b++)if((a&On[b])>>>0==Pn[b]){b=!0;break a}b=!1}return b},Tn=null,Un=null;var Zn=null,$n=null,ao=function(){Zn||(Zn=new ej(3,"dial.DialOnDeviceListEventListener","mr.dial.SinkDiscoveryService",chrome.dial.onDeviceList));$n||($n=new ej(4,"dial.DialOnErrorEventListener","mr.dial.SinkDiscoveryService",chrome.dial.onError));return[Zn,$n]};var bo=function(a,b){b=void 0===b?new Vn:b;this.Dt=a;this.cM=b;this.a=D("mr.dial.SinkDiscoveryService");this.Ed=new Map;this.yx=this.bF=!1;this.Ng={vn:0,Lo:0};this.sv=0};ja(bo,uh);d=bo.prototype;d.init=function(){Wh(this);Eh("mr.dial.SinkDiscoveryService",this)};d.start=function(){this.bF||(this.a.info("Starting..."),this.bF=!0,ao().forEach(function(a){return a.addListener()}),this.refresh())};
d.refresh=function(){var a=this;this.bF?chrome.dial.discoverNow(function(b){a.a.info("chrome.dial.discoverNow = "+b)}):this.a.info("Not started. Ignoring discover().")};
d.Sba=function(a){var b=this;this.a.info("onDeviceList returned "+a.length+" devices");this.a.C(function(){return"....the list is: "+JSON.stringify(a)});this.yx=!1;var c=0,e=[],f=new Set;a.forEach(function(a){e.push(b.Aea(a).then(function(a){f.add(a.getId());b.xaa(a)},function(){c++}))});kj(e).then(function(){b.yx||b.Rx(f).then(function(){var a=b.Ed.size;b.AU(a,a+c)})})};
d.AU=function(a,b){this.Ng={vn:a,Lo:b};36E5>Date.now()-this.sv||(a=this.Ng,hh("MediaRouter.Dial.AvailableDevicesCount",a.vn),hh("MediaRouter.Dial.KnownDevicesCount",a.Lo),this.sv=Date.now())};d.xaa=function(a){if(!this.yx){this.a.C("mayAddSink, id = "+a.getId());var b=this.Ed.get(a.getId());b?b.update(a)&&(this.a.C("Updated sink "+b.getId()),this.Dt.Ee(b)):(this.a.C(function(){return"Adding new sink "+a.getId()+": "+a.SX()}),this.Ed.set(a.getId(),a),this.Dt.fm(a))}};
d.Rx=function(a){var b=this,c=[],e=[];this.Ed.forEach(function(f){a.has(f.getId())||e.push(b.Z1(f).then(function(a){a||(b.Ed.delete(f.getId()),c.push(f))}))});return kj(e).then(function(){0<c.length&&b.Dt.fg(c)})};d.Z1=function(a){return a.Rh?this.cM.Cq(a.Rh):Promise.resolve(!1)};
d.Aea=function(a){return this.cM.c6(a).then(function(b){var c;b.uniqueId?(c=b.uniqueId,0==c.indexOf("uuid:")&&(c=c.substr(5)),c=c.replace(/-/g,"").toLowerCase()):c="";var e=b.uniqueId?Pi.ga().Zn(c):a.deviceLabel,f=co.test(b.modelName);return(new Qi(b.friendlyName,c)).Iy(e).dja(b.ipAddress).Dia(b.appUrl).Bia(a.deviceDescriptionUrl).yja(b.modelName).kX(!f)})};
d.Oca=function(a){switch(a.code){case "no_valid_network_interfaces":case "network_disconnected":this.a.u("DIAL error: "+a.code+". Clear device list now.");a=Array.from(this.Ed.values());this.Ed.clear();this.Dt.fg(a);this.AU(0,0);this.yx=!0;break;case "no_listeners":case "socket_error":case "cellular_network":case "unknown":this.a.u("DIAL error: "+a.code+". Keep device list.");break;default:this.a.u("Unhandled DIAL error: "+a.code)}};d.pa=function(a){return this.Ed.get(a)||null};
d.Z7=function(a){var b=[];this.Ed.forEach(function(c){"available"==c.Pf(a)&&b.push(c.Bj())});var c=eo[a];return new Lk(b,c?[c]:void 0)};d.gf=function(){return Array.from(this.Ed.values())};d.wba=function(a,b){this.Dt.Ee(b)};d.handleEvent=function(a,b){for(var c=[],e=1;e<arguments.length;++e)c[e-1]=arguments[e];if(a==chrome.dial.onDeviceList)this.Sba.apply(this,[].concat(ka(c)));else if(a==chrome.dial.onError)this.Oca.apply(this,[].concat(ka(c)));else throw Error("Unhandled event");};d.Ca=function(){return"dial.DialSinkDiscoveryService"};
d.getData=function(){return[new fo(Array.from(this.Ed),this.Ng),{deviceCountMetricsRecordTime:this.sv}]};d.tb=function(){var a=Th(this);if(a){for(var b=ia(a.sinks),c=b.next();!c.done;c=b.next())c=c.value,this.Ed.set(c[0],Ri(c[1]));this.Ng=a.deviceCounts}if(a=Uh(this))this.sv=a.deviceCountMetricsRecordTime};
var eo={YouTube:"https://www.youtube.com",Netflix:"https://www.netflix.com",Pandora:"https://www.pandora.com",Radio:"https://www.pandora.com",Hulu:"https://www.hulu.com",Vimeo:"https://www.vimeo.com",Dailymotion:"https://www.dailymotion.com","com.dailymotion":"https://www.dailymotion.com"},co=/Eureka Dongle|Chromecast Audio/i,fo=function(a,b){this.sinks=a;this.deviceCounts=b};var go=function(a,b){this.a=D("mr.dial.AppDiscoveryService");this.Ad=new Set;this.sa=a;this.oe=b;this.uc=new Map;this.vB=new Map;this.tg=null;this.sp=!1};d=go.prototype;d.init=function(){Wh(this)};d.start=function(){this.a.info("Starting periodic scanning.");this.sp||(this.sp=!0,this.nM())};d.stop=function(){this.a.info("Stopping periodic scanning.");this.sp&&(this.sp=!1,this.tg&&(clearTimeout(this.tg),this.tg=null),this.uc.clear(),this.vB.forEach(function(a){a.abort()}))};
d.GG=function(a){if(!this.Ad.has(a)||this.E0(a))this.Ad.add(a),0!=this.sa.Ed.size&&(this.sp?this.sa.gf().forEach(this.mM.bind(this,a)):this.start())};d.AI=function(a){this.Ad.delete(a)};d.B7=function(){return Array.from(this.Ad)};
d.nM=function(){var a=this;this.a.info("Start app status scan.");var b=[];this.sa.gf().forEach(function(c){b.push.apply(b,a.mt(c))});this.oe.Z4().forEach(function(c){b.push(a.Tga(c))});kj(b).then(function(){a.sp&&!a.tg&&(a.a.C("Scan complete; scheduling for next scan."),a.tg=setTimeout(function(){a.P3()},6E4))})};d.P3=function(){this.a.C("Start app status scan (timer-based)");this.tg=null;this.nM()};
d.mt=function(a){if(!a.Op)return[];for(var b=[],c=ia(this.Ad),e=c.next();!e.done;e=c.next())b.push(this.mM(e.value,a));return b};d.mM=function(a,b){if("unknown"!=b.Pf(a)&&36E5>Date.now()-b.f5(a)||!b.Op)return Promise.resolve();this.a.C("Querying "+b.getId()+" for "+a+" to update app status");return this.hN(b,a).then(this.Haa.bind(this,b,a))};
d.Tga=function(a){var b=this.sa.pa(a.Gb.sinkId);if(!b)return this.a.u("Activity refers to nonexistent sink: "+a.Gb.id),Promise.resolve();if(!b.Op)return Promise.resolve();a=a.appName;this.a.C("Querying "+b.getId()+" for "+a+" to update activity");return this.hN(b,a).then(this.Gaa.bind(this,b,a))};d.e6=function(a){var b=this.vB.get(a.getId());b||(b=new zn(a),this.a.C("Created DIAL client for "+a.getId()),this.vB.set(a.getId(),b));return b};
d.hN=function(a,b){var c=this,e=ho(a,b),f=this.uc.get(e);if(f)return f;f=this.e6(a).pC(b);this.uc.set(e,f);a=function(){c.uc.delete(e)};f.then(a,a);return f};d.n5=function(a,b){if(404==b.jZ.Sa())return"unavailable";b=b.Eh;if("Netflix"==a)return this.e5(b);switch(b.state){case "running":case "stopped":return"available";default:return"unavailable"}};d.e5=function(a){return!a.extraData||"websocket"!=a.extraData.capabilities||"running"!=a.state&&"stopped"!=a.state?"unavailable":"available"};
var ho=function(a,b){return a.getId()+":"+b};d=go.prototype;d.Haa=function(a,b,c){if(404==c.jZ.Sa()||c.Eh){c=this.n5(b,c);this.a.C("Got app status "+c+" from "+a.getId()+" for "+b);var e=a.Pf(b);a.rt(b,c);c!=e&&this.sa.wba(b,a)}else this.a.u("Failed to process app availability; "+a.getId()+" does not support app availability"),a.kX(!1)};d.Gaa=function(a,b,c){(a=this.oe.tN(a.getId()))&&a.appName==b&&!c.Qga&&this.oe.KU(a.Gb.id)};
d.E0=function(a){return this.sa.gf().some(function(b){return"unknown"==b.Pf(a)})};d.Ca=function(){return"dial.AppDiscoveryService"};d.getData=function(){return[this.B7()]};d.tb=function(){var a=Th(this);this.Ad=new Set(a||[])};var io=function(a,b,c){this.L=a;this.Dd=b||new bo(this);this.oe=new In(this);this.pe=c||new go(this.Dd,this.oe);this.a=D("mr.DialProvider")};d=io.prototype;d.getName=function(){return"dial"};d.Tb=function(){this.oe.init();this.Dd.init();this.Dd.start();this.pe.init();this.Ds()};d.ir=function(a){this.a.C("GetAvailableSinks for "+a);return(a=Dn(a))?this.Dd.Z7(a.appName):Mk};d.startObservingMediaSinks=function(a){if(a=Dn(a))this.pe.GG(a.appName),this.Ds()};
d.stopObservingMediaSinks=function(a){if(a=Dn(a))this.pe.AI(a.appName),this.ox()};d.startObservingMediaRoutes=function(){this.Ds()};d.stopObservingMediaRoutes=function(){this.ox()};d.ox=function(){(0==this.Dd.Ed.size||0==this.pe.Ad.size&&0==this.oe.He.size)&&this.pe.stop()};d.Ds=function(){0<this.Dd.Ed.size&&(0<this.pe.Ad.size||0<this.oe.He.size)&&this.pe.start()};d.pa=function(a){return(a=this.Dd.pa(a))?a.Bj():null};d.li=function(){return this.oe.li()};
d.createRoute=function(a,b,c,e){var f=this,h=this.Dd.pa(b);if(!h)return Ln(0),Pg(Error("Unkown sink: "+b));Pi.ga().sm=new Oi(h.xd,h.Ga);var k=Dn(a);if(!k)return Pg(Error("No app name set."));var n=k.appName,q=this.aT(h);return Qg(q.pC(n).then(function(a){if(!a.Eh)throw Error("Failed to get app info");if("running"==a.Eh.state)return q.BX(n)}).then(function(){return q.launchApp(n,k.launchParameter)}).then(function(){return f.Dg(b,a,!0,n,c,e)}).catch(function(a){Ln(3);throw a;}))};d.joinRoute=function(){return Pg(Error("Not supported"))};
d.connectRouteByRouteId=function(){return Pg(Error("Not supported"))};d.detachRoute=function(){};d.Dg=function(a,b,c,e,f,h){Ln(1);a=ni(f,this.getName(),a,b,c,e,null);a.offTheRecord=h;this.oe.add(new Hn(a,e));return a};d.fm=function(a){this.L.onSinkAvailabilityUpdated(this,1);this.Ds();this.pe.mt(a);this.L.sf();Pi.ga().rm=new Oi(a.xd,a.Ga)};d.fg=function(a){var b=this;if(0==this.Dd.Ed.size)this.L.onSinkAvailabilityUpdated(this,0);this.ox();a.forEach(function(a){b.oe.Lfa(a.getId())});this.L.sf()};
d.Ee=function(){this.L.sf()};d.nba=function(a){this.Ds();this.L.em(this,a.Gb)};d.iT=function(a){a=a.Gb;if(a.isLocal)this.L.onPresentationConnectionStateChanged(a.id,"terminated");this.ox();this.L.Vj(this,a)};d.terminateRoute=function(a){var b=this.oe.sN(a);if(!b)return Promise.reject(new Kk(3,"Route in DIAL provider not found for routeId "+a));this.oe.KU(a);return(a=this.Dd.pa(b.Gb.sinkId))?this.aT(a).BX(b.appName):Promise.reject(new Kk(3,"Sink in DIAL provider not found for sinkId "+b.Gb.sinkId))};
d.qo=function(){return null};d.po=function(){return null};d.sendRouteMessage=function(){return Promise.reject(Error("DIAL sending messages is not supported"))};d.sendRouteBinaryMessage=function(){return Promise.reject(Error("DIAL sending messages is not supported"))};d.Aq=function(a,b){b=this.Dd.pa(b);return!b||qh(a)?!1:(a=Dn(a))?"available"==b.Pf(a.appName):!1};d.zn=function(){return!1};d.searchSinks=function(){return null};d.aT=function(a){return new zn(a)};var jo=function(a,b){this.V1=a;this.QB=b;this.ij=this.V1.sa;this.a=D("mr.cast.CastDialSinkDiscoveryCallbacks")};d=jo.prototype;d.S3=function(a){return this.ij.Cq(a)};d.eQ=function(a){var b=this.ij.pa(a.getId());return b?b:(a=a.Ga)?this.ij.X7(a,Pi.ga().Cn||8009):null};d.fm=function(a){this.eQ(a)?cj(2):this.fY(a);this.QB.fm(a)};d.fY=function(a){var b=this,c=Ti(a);c&&this.S3(c).then(function(e){e?b.eQ(a)?cj(2):(b.ij.rq(c),cj(0)):fh("MediaRouter.Dial.Sink.Discovered.NonCast")},na)};
d.fg=function(a){var b=this;x(a,function(a){var c=b.ij.pa(a.getId());c&&c.Rn&&b.ij.wm(a.getId())});this.QB.fg(a)};d.Ee=function(a){var b=this.ij.pa(a.getId());b?b.Rn&&(b.update(a.jo(),a.Ga,b.sb(),b.Zd)&&this.a.info("Updated Cast sink with DIAL sink: "+a.getId()),this.ij.Ee(b)):this.fY(a);this.QB.Ee(a)};var ko=function(a,b){this.sa=new bo(new jo(b,this));this.Bm=new H;this.L=a;this.qt=this.Im=0;this.rs=new Ee;this.Cb=new io(this,this.sa)};d=ko.prototype;d.Ca=function(){return"cast.DialProviderWrapper"};d.getData=function(){return[new lo(this.Bm.g(),this.Im,this.qt,this.rs.T())]};d.tb=function(){var a=Th(this);a&&(this.Bm.addAll(a.Gga),this.Im=a.sequenceNumber,this.qt=a.Eha,this.rs.addAll(a.W$))};d.getName=function(){return this.Cb.getName()};d.Tb=function(){this.Cb.Tb();Wh(this)};d.li=function(){return this.Cb.li()};
d.zT=function(){};d.ir=function(a){return this.Cb.ir(a)};d.startObservingMediaSinks=function(a){this.Cb.startObservingMediaSinks(a)};d.stopObservingMediaSinks=function(a){this.Cb.stopObservingMediaSinks(a)};d.startObservingMediaRoutes=function(a){this.Cb.startObservingMediaRoutes(a)};d.stopObservingMediaRoutes=function(a){this.Cb.stopObservingMediaRoutes(a)};d.pa=function(a){return this.Cb.pa(a)};d.Xv=function(a){return new zn(a)};d.NC=function(a){return this.sa.pa(a)};
d.N3=function(a,b,c,e){var f=this,h=Dn(a),k=this.NC(b);if(!k)return Promise.reject(Error("Attempting custom launch with closed route"));var n=h.appName;if(!n)return Promise.reject(Error("No app name given"));var q=kk(a);if(!q)return Promise.reject(Error("No client ID"));var z=null;return this.Xv(k).pC(n).then(function(a){if(!a.Eh)return Promise.reject(Error("Failed to get app info"));z=a.Eh}).then(function(){return f.Cb.Dg(b,a,!0,n,e,c)}).then(function(a){var b={routeId:a.id,sinkId:k.getId(),appName:n,
Eh:z,launchParameter:h.launchParameter,session:null,clientId:null};f.Bm.set(a.id,b);f.X2(b,q);return a})};d.p$=function(a){return mo.test(a)};d.createRoute=function(a,b,c,e,f,h,k){return this.p$(a)?Qg(this.N3(a,b,e,c)):this.Cb.createRoute(a,b,c,e,f,h,k)};
d.terminateRoute=function(a){var b=this.Bm.get(a);if(b&&b.session&&b.clientId){var c={receiver:this.GB(b.sinkId),action:chrome.cast.nq.STOP},c=new Rj("receiver_action",c);c.clientId=b.clientId;this.L.eg(this,b.routeId,c);this.L.onPresentationConnectionStateChanged(b.routeId,"terminated")}return this.Cb.terminateRoute(a)};
d.sendRouteMessage=function(a,b,c){var e=JSON.parse(b);switch(e.type){case "client_connect":return this.cga(a,e.clientId);case "custom_dial_launch":if(this.rs.contains(e.sequenceNumber))return this.Iba(a,e);break;case "v2_message":if("STOP"==e.message.type)return this.terminateRoute(a),Promise.resolve()}return this.Cb.sendRouteMessage(a,b,c)};d.sendRouteBinaryMessage=function(a){return Promise.reject(Error("Route "+a+" does not support sending binary data."))};
d.Y6=function(){var a=String(this.qt);this.qt=(this.qt+1)%9007199254740992;return a};d.X2=function(a,b){var c=this.GB(a.sinkId),e=new Rj("receiver_action",{receiver:c,action:chrome.cast.nq.CAST});e.clientId=b;this.L.eg(this,a.routeId,e);c=new chrome.cast.M(this.Y6(),"",a.appName,[],c);a.session=c;a.clientId=b;c=new Rj("new_session",c);c.clientId=b;this.L.eg(this,a.routeId,c)};
d.Iba=function(a,b){this.rs.remove(b.sequenceNumber);b=b.message;a=this.Bm.get(a);if(!a)return Promise.reject(Error("Unknown route"));if(b&&!b.doLaunch)return Promise.resolve();var c=this.NC(a.sinkId);if(!c)return Promise.reject(Error("Custom launch response for sink that no longer exists"));var c=new zn(c),e=a.launchParameter,e=(b?b.launchParameter:null)||e;return c.launchApp(a.appName,e)};
d.GB=function(a){var b=this.NC(a);a=new chrome.cast.rA(a,b.jo());a.ipAddress=b.Ga;a.receiverType=chrome.cast.ou.DIAL;return a};d.X6=function(){var a=this.Im;this.Im=(this.Im+1)%9007199254740992;return a};
d.cga=function(a,b){a=this.Bm.get(a);if(!a)return Promise.reject(Error("Unknown route"));var c=this.GB(a.sinkId);c.receiverType=chrome.cast.ou.DIAL;c=new Rj("custom_dial_launch",new chrome.cast.BJ(c,a.Eh.state,a.Eh.extraData));c.clientId=b;c.sequenceNumber=this.X6();this.rs.add(c.sequenceNumber);this.L.eg(this,a.routeId,c);return Promise.resolve()};d.qo=function(a){return this.Cb.qo(a)};d.po=function(a){return this.Cb.po(a)};d.Aq=function(a,b){return this.Cb.Aq(a,b)};
d.zn=function(a,b,c){return this.Cb.zn(a,b,c)};d.connectRouteByRouteId=function(a,b,c,e,f){return this.Cb.connectRouteByRouteId(a,b,c,e,f)};d.joinRoute=function(a,b,c,e,f,h){return this.Cb.joinRoute(a,b,c,e,f,h)};d.detachRoute=function(a){this.Bm.remove(a);this.Cb.detachRoute(a)};d.sf=function(){this.L.sf()};d.onSinkAvailabilityUpdated=function(a,b){this.L.onSinkAvailabilityUpdated(a,b)};d.em=function(a,b){this.L.em(this,b)};d.Vj=function(a,b){this.L.Vj(this,b)};
d.Wj=function(a,b){this.L.Wj(this,b)};d.eg=function(a,b,c){this.L.eg(this,b,c)};d.onPresentationConnectionStateChanged=function(a,b){this.L.onPresentationConnectionStateChanged(a,b)};d.onPresentationConnectionClosed=function(a,b,c){this.L.onPresentationConnectionClosed(a,b,c)};d.yD=function(a){return this.L.yD(a)};d.LD=function(){return this.L.LD()};d.ei=function(){return this.L.ei()};d.Cx=function(a,b,c){this.L.Cx(this,b,c)};d.IF=function(a){this.L.IF(a)};d.fm=function(a){this.Cb.fm(a)};d.fg=function(a){this.Cb.fg(a)};
d.Ee=function(a){this.Cb.Ee(a)};d.Kt=function(){};d.Mz=function(){};d.searchSinks=function(a,b){return this.Cb.searchSinks(a,b)};d.HG=function(a){this.L.HG(a)};d.BE=function(){return this.L.BE()};d.np=function(a,b){return this.L.np(a,b)};var lo=function(a,b,c,e){this.Gga=a;this.sequenceNumber=b;this.Eha=c;this.W$=e},mo=/__dialAppName__/;var no=function(a,b){this.Gb=a;this.Kla=b;this.Bi=new Ec;this.R=this.Bi.promise;this.ec=Lg.gw(a.id);this.Gd=new Ec;this.ie=!1;this.Bt();this.cI();this.Xb(new Lh("GET_TURN_CREDENTIALS"))};d=no.prototype;d.start=function(){var a=this;return this.R.then(function(b){if(b.Jj())return Promise.reject(Error("Presentation already started"));b.start();return a.Gd.promise})};d.stop=function(){var a=this;this.ie=!1;return this.R.then(function(b){b.stop();a.R=Promise.reject(Error("Peer connection has already been stopped"))})};
d.Bt=function(){var a=this;this.ec.onMessage=function(b){if(b.type)switch(b.type){case "TURN_CREDENTIALS":a.Bi.resolve(new Ph(a.Gb.id,b.data.credentials));break;case "ANSWER":a.R.then(function(a){a.setRemoteDescription(b.data)});break;case "STOP":a.Gd.reject("Stop signal received");a.stop();break;default:throw Error("Unknown message type: "+b.type);}else a.R.then(function(a){a.fha({type:"PRESENTATION_CONNECTION_MESSAGE",data:b})})}};
d.cI=function(){var a=this;this.R.then(function(b){b.JW(function(b){a.Xb(new Lh("OFFER",new Nh(b,null,null,a.Kla)))});b.IW(function(b){b=Mh(b);"STOP"==b.type&&a.stop();a.Xb(b)});b.HW(function(){a.ie=!0;a.Xb(new Lh("SESSION_START_SUCCESS"));a.Gd.resolve(a.Gb)});b.FW(function(){a.Xb(new Lh("SESSION_END"))});b.GW(function(b){a.ie||a.Gd.reject(b);a.Xb(new Lh("SESSION_FAILURE"))})})};d.Xb=function(a){this.ec.sendMessage(a,oo)};var oo={channelType:"cloud"};var po=function(a){this.L=a;this.Ab=new Map;this.my=new Map;this.Et=[];this.qg=this.Uo=this.td=this.Zh=this.wo=null;this.Yo=this.Nk=this.lj=!1;this.Ft=new Map;this.Tp=new Map;Wh(this)};d=po.prototype;d.getName=function(){return"cloud"};
d.Tb=function(){var a=this;this.a.info("Initializing Cloud MRP");var b=jn.ga(),c=b.J5(this);this.Et.push(c);this.wo=b.w6(this);this.Et.push(this.wo);this.Zh=b.mO();this.td=b.ci();this.Uo=b.Q6(this);this.qg=b.U7();this.qg.G5().then(function(b){a.lj=b;a.a.info("Cloud enabled setting: "+a.lj)});this.qg.I5().then(function(b){a.Nk=b;a.a.info("Cloud on setting: "+a.Nk)});this.qg.Pja(function(b){a.lj=b;a.a.info("Cloud enabled setting: "+a.lj);a.lj&&a.rR()});this.qg.a7().then(function(b){a.Yo=b;a.a.info("Privacy notified setting: "+
a.Yo)})};d.li=function(){return Array.from(this.Ab.values())};
d.ir=function(a){if(!this.zE(a))return Mk;this.a.C("GetAvailableSinks for "+a);var b=[];if(this.Nk||this.wla())b=this.rR();this.Tp.clear();for(var c={},e=ia(this.Ft.values()),f=e.next();!f.done;c={qp:c.qp,Qv:c.Qv},f=e.next())c.qp=f.value,c.Qv=!1,b.forEach(function(a){return function(b){b.yb.id==a.qp.yb.id&&(a.Qv=!0,b.yb.friendlyName=a.qp.yb.friendlyName)}}(c)),c.Qv||this.Tp.set(c.qp.yb.id,c.qp);b=b.concat.apply(b,[].concat(ka(this.Tp.values())));this.a.C(function(){return"Available sinks are..."+
JSON.stringify(b)});c=b.map(function(a){return a.yb});this.wo&&(c=c.concat(qo));return new Lk(c,-1!=a.indexOf("0F5096E8")?sh:null)};d.rR=function(){var a=[];this.a.info("Checking cloud discovery services");Pi.ga().Vw=u();this.Et.forEach(function(b){b=b.gf();a=a.concat(b)});return a};d.startObservingMediaSinks=function(){};d.stopObservingMediaSinks=function(){};d.startObservingMediaRoutes=function(){};d.stopObservingMediaRoutes=function(){};d.pa=function(a){return(a=this.lr(a))?a.yb:null};
d.createRoute=function(a,b,c,e,f,h,k){var n=this;this.a.info("createRoute called");this.a.C("urn: "+a+" sinkId:"+b);if(f=this.my.get(b))return this.L.Mz(this,f,a,c,k,function(b){b.mediaSource=a;b.lf.tabId=k;return Og(b)}).nB(function(a){n.L.Wj(n,a);return a});f=this.lr(b);return this.vv(a,f,b,c,e,h,k)};
d.OL=function(a,b,c,e){a instanceof Kk&&2==a.errorCode?this.Zm(b,6,null):(this.a.error("Error on start session",a instanceof Error?a:Error("Expected an Error value, got "+a)),this.Zm(b,e,new Mg(Sm,"warning","dismiss")));this.wo&&this.wo.Pfa(c)&&this.fg([c.yb])};
d.vv=function(a,b,c,e,f,h,k){var n=this;if(f)return Pg(Error("not supported"));f=!1;switch(this.xD(b)){case "cloud":hm(1);break;case "mesi":f=!0,this.Yo||(this.Yo=!0,this.qg.Oja(),h=new Mg(Vm,"notification","learn_more"),h.Fka(["dismiss"]),h.Zia(6320939),this.L.ei().send(h)),hm(0)}Pi.ga().sm=new Oi(b.model,null);var q=ni(e,this.getName(),c,a,!0,"",null);f&&(q.customControllerPath="cloud_route_details/view.html?routeId="+q.id);this.Ab.set(q.id,q);this.my.set(c,q);this.Ft.set(q.id,b);this.L.em(this,
q);this.L.np(this.Ca(),!0);if(rh(a)&&!f)return this.a.info("starting presentation on route: "+q.id),this.Tla(q,a).catch(function(a){n.OL(a,q,b,7);throw a;});this.a.info("starting mirroring on route: "+q.id);q.lf={tabId:k,sessionId:"",mI:"",tX:b.model};rh(a)&&(q.isOffscreenPresentation=!0);return this.L.Kt(this,q,e).catch(function(a){n.OL(a,q,b,5);throw a;})};
d.terminateRoute=function(a){var b=this.Ab.get(a);return b?this.Zm(b,0,null):Promise.reject(new Kk(3,"Route in cloud provider not found for routeId "+a))};
d.Zm=function(a,b,c){this.a.info("terminating route: "+a.id);this.Ab.delete(a.id);this.my.delete(a.sinkId);var e=this.Ft.get(a.id);this.Ft.delete(a.id);c&&this.ei().send(c);gh("MediaRouter.Cloud.Session.End",b,cm);switch(b){case 1:break;default:this.s2(e)}this.L.Vj(this,a);0==this.Ab.size&&this.L.np(this.Ca(),!1);this.L.onPresentationConnectionStateChanged(a.id,"terminated");this.Tp.has(a.sinkId)&&(b=this.Tp.get(a.sinkId),this.fg([b.yb]),this.Tp.delete(a.sinkId));return Promise.resolve()};
d.sendRouteMessage=function(a,b,c){if(c&&c.channelType){c=c.channelType;var e=(a=this.Ab.get(a)||void 0)?this.lr(a.sinkId):void 0;return this.Uo.Bea(c,b,a,e)}return p(b)?(this.Je(b,a),Promise.resolve()):Promise.reject(Error("Channel type missing"))};d.sendRouteBinaryMessage=function(a){return Promise.reject(Error("Route "+a+" does not support sending binary data."))};
d.qo=function(a){var b=new Kh;"hangouts"!=this.po(a)&&(b.senderSideLetterboxing=!0);b.vS();this.a.info("Settings for "+a+": "+b.Fz());return b.shouldCaptureAudio||b.shouldCaptureVideo?b:null};d.po=function(a){var b=null;a=this.lr(a);switch(this.xD(a)){case "cloud":b="webrtc";break;case "mesi":b=a.dh?"meetings":"hangouts"}return b};d.Aq=function(a,b){this.a.C("Checking canRoute: "+a+" for sinkId: "+b);return this.zE(a)&&!!this.pa(b)};
d.zn=function(a,b){return"https://hangouts.google.com/cloudmrp-mirroring"==a&&this.Ab.has(b)};d.joinRoute=function(a,b){return(a=this.Ab.get(b))?Og(a):Pg(Error("not supported"))};d.connectRouteByRouteId=function(){return Pg(Error("not supported"))};d.detachRoute=function(){};d.OF=function(a){this.a.info(a.length+" sinks added");0<a.length&&!this.Nk&&(this.qg.Nma(),this.Nk=!0);a=this.lr(a[0].id);Pi.ga().rm=new Oi(a.model,null);this.L.sf();this.L.onSinkAvailabilityUpdated(this,2);this.a.info("sinkAvailability changed to AVAILABLE")};
d.fg=function(a){this.a.info(a.length+" sinks removed");this.Et.some(function(a){return 0<a.gf().length})||(this.L.onSinkAvailabilityUpdated(this,0),this.a.info("sinkAvailability changed to UNAVAILABLE"));this.L.sf()};d.sf=function(a){this.a.info(a.length+" sinks updated");this.L.sf()};d.ei=function(){return this.L.ei()};d.Je=function(a,b,c){c?this.L.eg(this,b,a):this.L.Cx(this,b,a)};d.lr=function(a){var b=this.f6(a);b||(b=this.M7(a));return b};
d.f6=function(a){var b=null;this.Et.some(function(c){b=c.pa(a);return!!b});return b};d.M7=function(a){var b=null;(a=this.my.get(a))&&(b=this.Ft.get(a.id));return b};d.s2=function(a){switch(this.xD(a)){case "cloud":this.Zh.tha(a.deviceId)}};d.xD=function(a){return a.IX("cloud")?"cloud":a.IX("mesi")?"mesi":null};d.wla=function(){var a=Pi.ga().Vw;return 3E5<=Date.now()-a};
d.zE=function(a){var b=qh(a);a=rh(a);if(this.td.Ko&&!this.td.uh&&b)return this.L.onSinkAvailabilityUpdated(this,2),!0;var c=!1;this.lj&&this.td.uh&&(c=!0);return chrome.declarativeWebRequest||this.td.K$()||!a?c&&(b||a):!1};d.searchSinks=function(a,b){if(!this.zE(a))return null;(a=this.wo.h0(b))&&this.OF([a]);return a};d.Ca=function(){return"CloudProvider"};d.getData=function(){return[void 0,{cloudEnabled:this.lj,cloudOn:this.Nk,notifiedHangoutsPrivacy:this.Yo}]};
d.tb=function(){var a=Uh(this);a&&(a.cloudEnabled&&(this.lj=a.cloudEnabled),a.cloudOn&&(this.Nk=a.cloudOn),a.notifiedHangoutsPrivacy&&(this.Yo=a.notifiedHangoutsPrivacy))};d.Tla=function(a,b){a=new no(a,b);return Qg(a.start())};d.a=D("mr.CloudProvider");var qo=new zi("pseudo:cloud","","hangout","Add a hangout","default");var ro=function(){ej.call(this,12,"ExternalMessageListener","mr.ProviderManager",chrome.runtime.onMessageExternal)};ja(ro,ej);ro.prototype.Tz=function(a,b){return b.id&&-1!=so.indexOf(b.id)?"start"==a.type||"stop"==a.type:!1};ro.prototype.MB=function(){return!0};var uo=function(){to||(to=new ro);return to},to=null,so=["idmofbkcelhplfjnmmdolenpigiiiecc","ggedfkijiiammpnbdadhllnehapomdge","njjegkblellcjnakomndbaloifhcoccg"];var vo=function(){ej.call(this,11,"InternalMessageListener","mr.ProviderManager",chrome.runtime.onMessage)};ja(vo,ej);vo.prototype.Tz=function(a,b){return"retrieve_log_data"==a.type&&b.id==chrome.runtime.id&&b.url=="chrome-extension://"+b.id+"/feedback.html"};vo.prototype.MB=function(){return!0};var xo=function(){wo||(wo=new vo);return wo},wo=null;var yo,zo,Ao=D("mr.Init"),Bo=function(a){var b=new Xk(a),c=new ko(a,b),b=[b,c];b.push(new po(a));return b};jl.ga().init();yo=new ah("MediaRouter.Provider.WakeDuration");zo=new ql;
var Co=(new Promise(function(a,b){switch(window.location.host){case "enhhojjnijigcajfphajepfemndkmdlo":a();break;case "pkedcjkdefgpdelpbcmbmeomcjbeemfm":chrome.management.get("enhhojjnijigcajfphajepfemndkmdlo",function(c){chrome.runtime.lastError||!c.enabled?a():b(Error("Dev extension is enabled"))});break;default:b(Error("Unknown extension id"))}})).then(function(){return chrome.mojoPrivate&&chrome.mojoPrivate.requireAsync?new Promise(function(a){chrome.mojoPrivate.requireAsync("media_router_bindings").then(function(b){b.start().then(function(c){a({mrService:b,mrInstanceId:c})})})}):
Promise.reject(Error("No mojo service loaded"))}).then(function(a){if(!a.mrService)throw Error("Failed to get MR service");var b=a.mrInstanceId;if(!b)throw Error("Failed to get MR instance ID.");Ao.info("MR instance ID: "+b);a=a.mrService;if(!zo)throw Error("providerManager not initialized.");a.setHandlers(zo);Yh(b)&&yo.Ap("MediaRouter.Provider.FirstWakeDuration");chrome.runtime.onSuspend.addListener(yo.end.bind(yo));bi(b);jl.ga().wfa();b=Bo(zo);window.addEventListener("unhandledrejection",function(a){a=
a.reason;a.stack||(a=Error(a));Ao.error("Unhandled promise rejection.",a)});zo.Tb(a,b)}).then(void 0,function(a){Ao.u(a.message);throw a;});[].concat([uo(),xo()],ka(ao()),ka([hj(),jj()]),ka([mm()])).forEach(function(a){return a.o0()});uo().addListener();xo().addListener();Co.then(void 0,function(){return window.close()});
